name: 部署 solid_snake

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SET SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: deploy to ec2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-210-95-214.ap-southeast-2.compute.amazonaws.com << 'EOF'
            cd personalProject/
            git checkout develop
            git pull origin develop
            npm install
            pm2 restart develop
          EOF

